version: '3.8'

services:
    mongo:
        image: mongo
        # environment:
        #   - PUID=1000
        #   - PGID=1000

        volumes:
          - ./database:/data/db
        ports:
            - 27018:27017
            
        restart: unless-stopped